namespace Vigia.Models.Enums;

public enum ErrorCodes
{
    UNKNOWN_ERROR = 0,
    VALIDATION_ERROR = 1,
    USER_NAME_REQUIRED = 2,
    INVALID_EMAIL = 3,
    USER_EMAIL_IS_REQUIRED = 4,
    USER_NAME_IS_REQUIRED = 5,
    USER_PASSWORD_IS_REQUIRED = 6,
    USER_EMAIL_ALREADY_IN_USE = 7,
    USER_NOT_FOUND = 8,
    TOKEN_REQUIRED = 9,
    IP_REQUIRED = 10,
    EXPIRATION_DATE_INVALID = 11,
    USER_ID_REQUIRED = 12,
}