namespace Vigia.Models.Enums;

public enum ErrorCodes
{
    UNKNOWN_ERROR = 0,
    VALIDATION_ERROR = 1,
    USER_NAME_REQUIRED = 2,
    INVALID_EMAIL = 3,
    USER_EMAIL_IS_REQUIRED = 4,
    USER_NAME_IS_REQUIRED = 5,
    USER_PASSWORD_IS_REQUIRED = 6,
    USER_EMAIL_ALREADY_IN_USE = 7,
    USER_NOT_FOUND = 8,
    TOKEN_REQUIRED = 9,
    IP_REQUIRED = 10,
    EXPIRATION_DATE_INVALID = 11,
    USER_ID_REQUIRED = 12,
    DEVICE_ALREADY_IN_USE = 13,
    DEVICE_NAME_REQUIRED = 14,
    MAC_ADDRESS_REQUIRED = 15,
    INVALID_MAC_ADDRESS = 16,
    DEVICE_KEY_REQUIRED = 17,
    GROUP_NOT_FOUND = 18,
    USER_GROUP_REQUIRED = 19,
    DEVICE_NOT_FOUND = 20,
    INVALID_DEVICE_NAME = 21,
    INVALID_SIGN_PUBLIC_KEY = 22,
    SIGN_PUBLIC_KEY_REQUIRED = 23,
}