name: vigia_ui
description: "Cuidar de quem você ama, nunca foi tão fácil"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^17.3.0
  flutter_riverpod: ^3.3.2
  riverpod_annotation: ^4.0.3
  dio: ^5.10.0
  uuid: ^4.6.0
  video_player: ^2.13.0
  flutter_blue_plus: ^2.3.10
  permission_handler: ^12.0.3
  cryptography: ^2.9.0
  flutter_secure_storage: ^10.3.1
  wifi_scan: ^0.4.1+2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.15.0
  riverpod_generator: ^4.0.4


flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/videos/