version: '3.8'

services:
  vigia-integration:
    image: pedroreis16/vigia-integration:latest
    container_name: vigia-integration
    networks:
      - vigia-network

  vigial-fall-detection:
    image: pedroreis16/vigia-fall-detection:latest
    container_name: fall-detection
    networks:
      - vigia-network

networks:
  vigia-network:
    driver: bridge