name: Web Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release"
        required: true
        default: "1.0.0"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
